function_table = {
    'start':'Начало',
    'iraida':'Начало',
    'locked':'Чердак',
    'attic':'Чердак',
    'sit_on_the_steps':'Чердак',
    'ouch':'Ванная',
    'experiment':'Ванная',
    'find_a_hydrometer':'Переход в спальню',
    'bedroom':'Спальня',
    'compass':'Поиск компаса',
    'vitya':'Поиск компаса',
    'compass2':'Изобретение компаса',
    'hall':'Добыча учебника',
    'hallway':'Добыча иголки',
    'magnet':'Добыча магнита',
    'game_over2':'Неудача',
    'water':'Добыча магнита',
    'kitchen':'Сборка компаса',
    'fortune':'Фортуна',
    'vitya2':'Встреча с Витей',
    'good_end':'Счастливый конец',
    'phone_call':'Звонок',
    'uncomfortable':'Звонок',
    'uncomfortable2':'Звонок',
    'sunday':'Звонок',
    'game_over':'Неудача',
    'game_over3a':'Приход отца',
    'game_over3b':'Несчастный конец',
    'end':'Конец'
}
score_table = {
    'start':1,
    'iraida':1,
    'locked':2,
    'attic':2,
    'sit_on_the_steps':3,
    'ouch':3,
    'experiment':4,
    'find_a_hydrometer':5,
    'bedroom':5,
    'compass':6,
    'vitya':6,
    'compass2':7,
    'hall':8,
    'hallway':8,
    'magnet':9,
    'game_over2':0,
    'water':9,
    'kitchen':10,
    'fortune':11,
    'vitya2':16,
    'good_end':17,
    'phone_call':14,
    'uncomfortable':14,
    'uncomfortable2':14,
    'sunday':15,
    'game_over':0,
    'game_over3a':12,
    'game_over3b':13,
    'end':17
}